config/routes.rb
Rails.application.routes.draw do

  devise_for :administrators
  resources :role_collaborators

  resources :role_candidates

  resources :needs_analyses do
    collection do
      post 'edit_candidate' => 'needs_analyses#edit_candidate', as: :edit_candidate
      put 'update_candidate' => 'needs_analyses#update_candidate', as: :update_candidate
      post 'edit_collaborator' => 'needs_analyses#edit_collaborator', as: :edit_collaborator
      put 'update_collaborator' => 'needs_analyses#update_collaborator', as: :update_collaborator
    end
  end

  resources :activities

  devise_for :candidates, :controllers => { :registrations => :registrations }
  resources :candidates, only: [:index, :show, :destroy]
  resources :collaborations

  get '/candidates/:id(.:format)/collaborator' => 'candidates#collaborator_instructions', :as => :collaborator_instructions
  get '/candidates/:id(.:format)/instructions' => 'candidates#instructions', :as => :instructions
  get '/candidates/:id(.:format)/report' => 'candidates#report', :as => :report
  get '/admin' => 'pages#admin'

  root 'pages#home'

end

app/controllers/needs_analyses_controller.rb
class NeedsAnalysesController < ApplicationController
  before_action :authenticate_administrator!, only: :index
  before_action :set_needs_analysis, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @search = NeedsAnalysis.ransack(params[:q])
    @needs_analyses = @search.result
    @grouped_areas = @needs_analyses.group_by &:area
  end

  def show
    respond_with(@needs_analysis)
  end

  def new
    @needs_analysis = NeedsAnalysis.new
    respond_with(@needs_analysis)
  end

  def edit
  end

  def create
    @needs_analysis = NeedsAnalysis.new(needs_analysis_params)
    @needs_analysis.save
    respond_with(@needs_analysis)
  end

  def update
    @needs_analysis.update(needs_analysis_params)
    respond_with(@needs_analysis)
  end

  # Candidate's edit controllers

  def edit_candidate
    @candidate = current_candidate
    @needs_analyses = NeedsAnalysis.find(params[:needs_analysis_ids]).sort_by &:order_id
  end

  def update_candidate
    NeedsAnalysis.update(params[:needs_analyses].keys, params[:needs_analyses].values)
    current_candidate.increment!(:tdna_visits)
    flash[:notice] = "Responses saved successfully"
    redirect_to candidate_path(current_candidate)
  end

  # Collaborator's edit controllers

  def edit_collaborator
    @candidate = Candidate.find(session[:candidate_id])
    @needs_analyses = NeedsAnalysis.find(params[:needs_analysis_ids]).sort_by &:order_id
    @grouped_areas = @needs_analyses.group_by &:area
  end

  def update_collaborator
    NeedsAnalysis.update(params[:needs_analyses].keys, params[:needs_analyses].values)
    flash[:notice] = "Responses saved successfully"
    @candidate = Candidate.find(session[:candidate_id])
    @candidate.increment!(:collaborator_tdna_visits)
    session.delete(:candidate_id)
    redirect_to candidate_path(current_candidate)
  end

  def destroy
    @needs_analysis.destroy
    respond_with(@needs_analysis)
  end

  private
    def set_needs_analysis
      @needs_analysis = NeedsAnalysis.find(params[:id])
    end

    def needs_analysis_params
      params.require(:needs_analysis).permit(:candidate_id, :collaborator_id, :activity_id, :area_id, :order_id, :relevance, :interest, :skill, :current_relevance, :future_relevance)
    end
end

app/helpers/needs_analyses_helper.rb
module NeedsAnalysesHelper
end

app/views/needs_analyses/_button_columns.html.erb
<% for needs_analysis in @needs_analyses %>
	<%= simple_fields_for 'needs_analyses[]', needs_analysis do |f| %>
		<tr>
			
			<td style="vertical-align:middle"><%= needs_analysis.activity.name %></td>

			<!-- RELEVANCE -->

			<td style="text-align:center">
				<%= f.hidden_field :relevance, label: false %>

				<script type="text/javascript">

					<% (0..5).each do |i| %>
					$(function() {
						if ($('#needs_analyses_<%= needs_analysis.id %>_relevance').val() === '<%= i %>') {
							$('#relevance-button-<%= needs_analysis.id %>-<%= i %>').addClass('btn-success');
							$('#relevance-button-<%= needs_analysis.id %>-<%= i %>').removeClass('btn-default');
						}
					});
					<% end %>

				</script>

				<div class="button-wrapper">
				<% (0..5).each do |i| %>
					
					<a class='btn-relevance-<%= needs_analysis.id %> btn btn-xs btn-default' onclick="" id='relevance-button-<%= needs_analysis.id %>-<%= i %>' value='<%= i %>'><%= i %></a>

					<script type="text/javascript">
						$('#relevance-button-<%= needs_analysis.id %>-<%= i %>').click(function(){
							$('.btn-relevance-<%= needs_analysis.id %>').removeClass('btn-success');
							$('.btn-relevance-<%= needs_analysis.id %>').addClass('btn-default');
							$('#needs_analyses_<%= needs_analysis.id %>_relevance').val('<%= i %>');
							$('#relevance-button-<%= needs_analysis.id %>-<%= i %>').addClass('btn-success');
							$('#relevance-button-<%= needs_analysis.id %>-<%= i %>').removeClass('btn-default');
						});
					</script>

				<% end %>
				</div>
			</td>
			
			<!-- INTEREST -->

			<td style="text-align:center">
				<%= f.hidden_field :interest, label: false %>

				<script type="text/javascript">

					<% (0..5).each do |i| %>
					$(function() {
						if ($('#needs_analyses_<%= needs_analysis.id %>_interest').val() === '<%= i %>') {
							$('#interest-button-<%= needs_analysis.id %>-<%= i %>').addClass('btn-success');
							$('#interest-button-<%= needs_analysis.id %>-<%= i %>').removeClass('btn-default');
						}
					});
					<% end %>

				</script>

				<div class="button-wrapper">
				<% (0..5).each do |i| %>
					
					<a class='btn-interest-<%= needs_analysis.id %> btn btn-xs btn-default' onclick="" id='interest-button-<%= needs_analysis.id %>-<%= i %>' value='<%= i %>'><%= i %></a>

					<script type="text/javascript">
						$('#interest-button-<%= needs_analysis.id %>-<%= i %>').click(function(){
							$('.btn-interest-<%= needs_analysis.id %>').removeClass('btn-success');
							$('.btn-interest-<%= needs_analysis.id %>').addClass('btn-default');
							$('#needs_analyses_<%= needs_analysis.id %>_interest').val('<%= i %>');
							$('#interest-button-<%= needs_analysis.id %>-<%= i %>').addClass('btn-success');
							$('#interest-button-<%= needs_analysis.id %>-<%= i %>').removeClass('btn-default');
						});
					</script>

				<% end %>
				</div>
			</td>

			<!-- SKILL/CONFIDENCE -->

			<td style="text-align:center">
				<%= f.hidden_field :skill, label: false %>

				<script type="text/javascript">

					<% (0..5).each do |i| %>
					$(function() {
						if ($('#needs_analyses_<%= needs_analysis.id %>_skill').val() === '<%= i %>') {
							$('#skill-button-<%= needs_analysis.id %>-<%= i %>').addClass('btn-success');
							$('#skill-button-<%= needs_analysis.id %>-<%= i %>').removeClass('btn-default');
						}
					});
					<% end %>

				</script>

				<div class="button-wrapper">
				<% (0..5).each do |i| %>
					
					<a class='btn-skill-<%= needs_analysis.id %> btn btn-xs btn-default' onclick="" id='skill-button-<%= needs_analysis.id %>-<%= i %>' value='<%= i %>'><%= i %></a>

					<script type="text/javascript">
						$('#skill-button-<%= needs_analysis.id %>-<%= i %>').click(function(){
							$('.btn-skill-<%= needs_analysis.id %>').removeClass('btn-success');
							$('.btn-skill-<%= needs_analysis.id %>').addClass('btn-default');
							$('#needs_analyses_<%= needs_analysis.id %>_skill').val('<%= i %>');
							$('#skill-button-<%= needs_analysis.id %>-<%= i %>').addClass('btn-success');
							$('#skill-button-<%= needs_analysis.id %>-<%= i %>').removeClass('btn-default');
						});
					</script>

				<% end %>
				</div>
			</td>
		</tr>
	<% end %>
<% end %>

app/views/needs_analyses/_form.html.erb
<%= simple_form_for(@needs_analysis) do |f| %>
  <% if @needs_analysis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@needs_analysis.errors.count, "error") %> prohibited this needs_analysis from being saved:</h2>

      <ul>
      <% @needs_analysis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :candidate_id %><br>
    <%= f.text_field :candidate_id %>
  </div>
  <div class="field">
    <%= f.label :collaborator_id %><br>
    <%= f.number_field :collaborator_id %>
  </div>
  <div class="field">
    <%= f.label :activity_id %><br>
    <%= f.number_field :activity_id %>
  </div>
  <div class="field">
    <%= f.label :area_id %><br>
    <%= f.number_field :area_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :relevance %><br>
    <%= f.number_field :relevance %>
  </div>
  <div class="field">
    <%= f.label :interest %><br>
    <%= f.number_field :interest %>
  </div>
  <div class="field">
    <%= f.label :skill %><br>
    <%= f.number_field :skill %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/needs_analyses/edit.html.erb
<h1>Editing needs_analysis</h1>

<%= render 'form' %>

<%= link_to 'Show', @needs_analysis %> |
<%= link_to 'Back', needs_analyses_path %>

app/views/needs_analyses/edit_candidate.html.erb
<div class="row">

	<div class="col-lg-10 col-lg-offset-1 col-md-12">

		<h3>TDNA Matrix<br>
		<small>for <%= current_candidate.name %></small></h3>
		<br>

		<%= form_tag update_candidate_needs_analyses_path, :method => :put do %>

			<table class="table table-hover table-responsive">
				<thead>
					<th style="width:34%">Activity</th>
				    <th style="width:22%;text-align:center">Relevance to Current&nbsp;Role</th>
				    <th style="width:22%;text-align:center">Interest</th>
				    <th style="width:22%;text-align:center">Skill/Confidence</th>
				</thead>
				<tbody>
					<%= render 'needs_analyses/button_columns' %>
				</tbody>
			</table>

			<%= submit_tag "Save and Exit", class: "btn btn-success" %>

		<% end %>

	</div>

</div>

app/views/needs_analyses/edit_collaborator.html.erb
<div class="row">

	<div class="col-md-8 col-md-offset-2">

		<h3>TDNA Matrix<br>
		<small>for <%= @candidate.name %></small></h3>
		<br>

		<%= form_tag update_collaborator_needs_analyses_path, :method => :put do %>

			<table class="table table-hover">
			  <thead>
			    <tr>
					<th style="width:50%">Activity</th>
				    <th style="width:25%">Current Relevance</th>
				    <th style="width:25%">Future Relevance</th>
			    </tr>
			  </thead>
			  <tbody>
			    <% @grouped_areas.each do |area, needs_analyses| %>
			      <tr class="area-row">
			        <th style="vertical-align:bottom" scope="rowgroup" colspan="4"><%= area.name %></th>
			      </tr>
			    <% for needs_analysis in needs_analyses %>
				    <%= fields_for 'needs_analyses[]', needs_analysis do |f| %>
				      <tr>
							<td><%= needs_analysis.activity.name %></td>
							<td><%= f.check_box :current_relevance, label: false %></td>
							<td><%= f.check_box :future_relevance, label: false %></td>
				      </tr>
				    <% end %>
			    <% end %>
			  </tbody>
			  <% end %>
			</table>

			<br>
			<%= submit_tag "Save and Exit", class: "btn btn-success" %>

		<% end %>

	</div>

</div>

app/views/needs_analyses/index.html.erb
<%= search_form_for @search do |f| %>

<div class="row">
  <div class="col-md-2">
      <%= f.input :candidate_id_eq, collection: Candidate.all, label: 'Candidate', required: false %>
  </div>
  <div class="col-md-2">
      <%= f.input :relevance_eq, collection: [0,1,2,3,4,5], label: 'Relevance', required: false %>
  </div>
  <div class="col-md-2"> 
      <%= f.input :interest_eq, collection: [0,1,2,3,4,5], label: 'Interest', required: false %>
  </div>
  <div class="col-md-2">
      <%= f.input :skill_eq, collection: [0,1,2,3,4,5], label: 'Skill', required: false %>       
  </div>
  <div class="col-md-2">
      <%= f.input :current_relevance_eq, collection: [true, false], label: 'Current Relevance', required: false %>
  </div>
  <div class="col-md-2">
      <%= f.input :future_relevance_eq, collection: [true, false], label: 'Future Relevance', required: false %>
  </div>
</div>

<div class="row">
  <div class="col-md-12" style="margin-bottom:4em">
    <%= f.submit 'Search', class: "btn btn-primary" %>
    <%= link_to "Clear", needs_analyses_path, class: "btn btn-default", style: "margin-left:0.25em" %>
  </div>
</div>

<% end %>

<table class="table table-hover table-responsive">

    <thead>
    <tr>
      <th colspan="1" style="text-align:center"></th>
      <th colspan="3" class="candidate-columns">Candidate</th>
      <th colspan="2" style="text-align:center">Collaborator</th>
    </tr>
  </thead>

  <thead>
    <tr>
      <th style="width:50%">Activity</th>
      <th style="width:10%;text-align:center" class="left-column">Current<br>Relevance</th>
      <th style="width:10%;text-align:center">Interest</th>
      <th style="width:10%;text-align:center" class="right-column">Skill</th>
      <th style="width:10%;text-align:center">Current<br>Relevance</th>
      <th style="width:10%;text-align:center">Future<br>Relevance</th>
    </tr>
  </thead>

  <tbody>
    <% @grouped_areas.each do |area, needs_analyses| %>
      <tr class="area-row">
        <th style="vertical-align:bottom" scope="rowgroup" colspan="4"><%= area.name %></th>
      </tr>
    <% needs_analyses.each do |needs_analysis| %>
      <tr>
        <td><%= needs_analysis.activity.name %></td>
        <td class="left-column" style="text-align:center"><%= needs_analysis.relevance %></td>
        <td style="text-align:center"><%= needs_analysis.interest %></td>
        <td class="right-column" style="text-align:center"><%= needs_analysis.skill %></td>
        <td style="text-align:center"><%= needs_analysis.current_relevance %></td>
        <td style="text-align:center"><%= needs_analysis.future_relevance %></td>
      </tr>
    <% end %>
  </tbody>
  <% end %>
</table>

app/views/needs_analyses/new.html.erb
<h1>New needs_analysis</h1>

<%= render 'form' %>

<%= link_to 'Back', needs_analyses_path %>

app/views/needs_analyses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Candidate:</strong>
  <%= @needs_analysis.candidate %>
</p>

<p>
  <strong>Collaborator:</strong>
  <%= @needs_analysis.collaborator_id %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @needs_analysis.activity_id %>
</p>

<p>
  <strong>Area:</strong>
  <%= @needs_analysis.area_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @needs_analysis.order_id %>
</p>

<p>
  <strong>Relevance:</strong>
  <%= @needs_analysis.relevance %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @needs_analysis.interest %>
</p>

<p>
  <strong>Skill:</strong>
  <%= @needs_analysis.skill %>
</p>

<p>
  <strong>Current relevance:</strong>
  <%= @needs_analysis.current_relevance %>
</p>

<p>
  <strong>Future relevance:</strong>
  <%= @needs_analysis.future_relevance %>
</p>

<%= link_to 'Edit', edit_needs_analysis_path(@needs_analysis) %> |
<%= link_to 'Back', needs_analyses_path %>