config/routes.rb
Rails.application.routes.draw do

  devise_for :administrators
  resources :role_collaborators

  resources :role_candidates

  resources :needs_analyses do
    collection do
      post 'edit_candidate' => 'needs_analyses#edit_candidate', as: :edit_candidate
      put 'update_candidate' => 'needs_analyses#update_candidate', as: :update_candidate
      post 'edit_collaborator' => 'needs_analyses#edit_collaborator', as: :edit_collaborator
      put 'update_collaborator' => 'needs_analyses#update_collaborator', as: :update_collaborator
    end
  end

  resources :activities

  devise_for :candidates, :controllers => { :registrations => :registrations }
  resources :candidates, only: [:index, :show, :destroy]
  resources :collaborations

  get '/candidates/:id(.:format)/collaborator' => 'candidates#collaborator_instructions', :as => :collaborator_instructions
  get '/candidates/:id(.:format)/instructions' => 'candidates#instructions', :as => :instructions
  get '/candidates/:id(.:format)/report' => 'candidates#report', :as => :report
  get '/admin' => 'pages#admin'

  root 'pages#home'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :collaborations, dependent: :destroy
	has_many :collaborators, :through => :collaborations
	has_many :inverse_collaborations, :class_name => "Collaboration", :foreign_key => "collaborator_id"
	has_many :inverse_collaborators, :through => :inverse_collaborations, :source => :candidate
	has_one :needs_analysis
	has_one :role_candidate
	has_one :role_collaborator

	validates :collaborator_id, numericality: { only_integer: true }, presence: true
	validates_presence_of :first_name, :last_name, :email
	
	# Custom validation for checking the existance of the Collaborator in the Candidate model

	validate :collaborator_check, on: :create
 
	def collaborator_check
		errors.add(:collaborator_id, "Please use a valid code.") unless Candidate.find_by_id(self.collaborator_id).present?
	end

	# Randomise the Candidate ID (before create)
	before_create :randomise_id

	# Create the required collaborations and responses (after create)
	after_create	:create_collaboration,
					:create_needs_analysis,
					:create_role_candidate,
					:create_role_collaborator

	# Destroy any collaborations (before destroy)
	before_destroy	:delete_collaboration

	def name
		first_name + " " + last_name
	end

	private

	def randomise_id
		begin
			self.id = SecureRandom.random_number(1_000_000)
		end while Candidate.where(id: self.id).exists?
	end

	def collaborator_id_exists
  		return false if Candidate.find_by_id(self.collaborator_id).nil?
	end

	def create_needs_analysis
		@activities = Activity.all
		@activities.each do |a|
			@needs_analysis = NeedsAnalysis.new
			@needs_analysis.candidate_id = self.id
			@needs_analysis.activity_id = a.id
			@needs_analysis.area_id = a.area_id
			@needs_analysis.order_id = a.order_id
			@needs_analysis.collaborator_id = self.collaborator_id
			@needs_analysis.save
		end
	end

	def create_role_candidate
		@role_candidate = RoleCandidate.new
		@role_candidate.candidate_id = self.id
		@role_candidate.save
	end

	def create_role_collaborator
		@role_collaborator = RoleCollaborator.new
		@role_collaborator.candidate_id = self.id
		@role_collaborator.collaborator_id = self.collaborator_id
		@role_collaborator.save
	end

	def create_collaboration
		@collaboration = Collaboration.new
		@collaboration.candidate_id = self.collaborator_id
		@collaboration.collaborator_id = self.id
		@collaboration.category = 'superior'
		@collaboration.save
	end

    def delete_collaboration
    	@collaboration = Collaboration.find_by('collaborator_id = ?', self.id)
    	@collaboration.destroy
    end

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
	before_action :authenticate_administrator!, only: [:index, :report]
	before_action :authenticate_candidate!, only: [:show]

	def index
		@candidates = Candidate.all.order(:created_at)
	end

	def show
		@candidate = Candidate.find(params[:id])
		@needs_analyses = NeedsAnalysis.where('candidate_id = ?', params[:id])
		@role_candidates = RoleCandidate.where('candidate_id = ?', params[:id])
		@role_collaborator = RoleCollaborator.where('collaborator_id = ?', params[:id])
	end

	def report
		@disable_nav = true
		@candidate = Candidate.find(params[:id])
		@collaborator = Candidate.find(@candidate.collaborator_id)
		@role_candidate = @candidate.role_candidate
		@role_collaborator = @candidate.role_collaborator
		@search = NeedsAnalysis.ransack(params[:q])
		@needs_analyses = @search.result.where('candidate_id = ?', params[:id])
		@grouped_areas = @needs_analyses.group_by &:area

		respond_to do |format|
			format.html
			format.pdf do
				pdf = ReportPdf.new(@candidate)
				send_data pdf.render, filename: 'report.pdf', type: 'application/pdf', disposition: 'inline'
			end
		end

	end

	def collaborator_instructions
		@candidate = Candidate.find(params[:id])
		session[:candidate_id] = @candidate.id
		redirect_to root_path, notice: "You are not authorised to access this." if @candidate.collaborator_id != current_candidate.id
		@needs_analyses = NeedsAnalysis.where('candidate_id = ?', params[:id])
		@role_candidates = RoleCandidate.where('candidate_id = ?', params[:id])
	end

	def instructions
		@candidate = Candidate.find(params[:id])
		@needs_analyses = NeedsAnalysis.where('candidate_id = ?', params[:id])
	end

	def destroy
		@candidate = Candidate.find(params[:id])
		@candidate.destroy
		flash[:notice] = "Candidate successfully deleted"
	  	redirect_to candidates_path
	end

end

app/views/candidates/_role_report.html.erb
<h3>Role Analysis</h3><br>

<div class="report-section">

	<h3><small>Previous, Current and Next Roles</small></h3><br>

	<table class="table table-hover">
		<thead>
			<th style="width:26%"></th>
			<th style="width:37%">Candidate</th>
			<th style="width:37%">Manager</th>
		</thead>
		<tbody>
			<tr>
				<td style="width:26%">Last Update</td>
				<td style="width:37%"><%= @role_candidate.updated_at.strftime("%-d %B %Y, %H:%m") %></td>
				<td style="width:37%"><%= @role_collaborator.updated_at.strftime("%-d %B %Y, %H:%m") %></td>
			</tr>
			<tr>
				<td style="width:26%">Name</td>
				<td style="width:37%"><strong><%= @candidate.name %></strong><br><%= @candidate.organisation_name %></td>
				<td style="width:37%"><strong><%= @collaborator.name %></strong><br><%= @collaborator.organisation_name %></td>
			</tr>
			<tr>
				<td style="width:26%">Previous Role</td>
				<td style="width:37%"><%= @role_candidate.previous_role %></td>
				<td style="width:37%">-</td>
			</tr>
			<tr>
				<td>Current Role</td>
				<td><%= @role_candidate.current_role %> (<%= @role_candidate.time_in_role %>)</td>
				<td><%= @role_collaborator.current_role %></td>
			</tr>
			<tr>
				<td>Next Role</td>
				<td><%= @role_candidate.next_role %></td>
				<td><%= @role_collaborator.next_role %></td>
			</tr>
			<tr>
				<td>Qualifications</td>
				<td colspan="2"><%= simple_format(@role_candidate.qualifications) %></td>
			</tr>
			<tr>
				<td>Context of Previous Role</td>
				<td><%= @role_candidate.previous_role_context %></td>
				<td>-</td>
			</tr>
			<tr>
				<td>Content of Current Role</td>
				<td><%= @role_candidate.current_role_context %></td>
				<td><%= @role_collaborator.current_role_context %></td>
			</tr>
			<tr>
				<td>Content of Next Role</td>
				<td><%= @role_candidate.next_role_context %></td>
				<td><%= @role_collaborator.next_role_context %></td>
			</tr>
		</tbody>
	</table>
</div>

<div class="row">
	<div class="col-md-6">

		<div class="report-section">
			<h3><small>Main Aspects of Current Role (Candidate)</small></h3><br>

			<table class="table table-hover">
				<thead>
					<th style="width:80%">Aspect</th>
					<th style="width:10%;text-align:center">Imp.</th>
					<th style="width:10%;text-align:center">Enj.</th>
				</thead>
				<tbody>
					<tr>
						<td><%= @role_candidate.main_aspect_a %></td>
						<td style="text-align:center"><%= @role_candidate.main_aspect_importance_a %></td>
						<td style="text-align:center"><%= @role_candidate.main_aspect_enjoyment_a %></td>
					</tr>
					<tr>
						<td><%= @role_candidate.main_aspect_b %></td>
						<td style="text-align:center"><%= @role_candidate.main_aspect_importance_b %></td>
						<td style="text-align:center"><%= @role_candidate.main_aspect_enjoyment_b %></td>
					</tr>
					<tr>
						<td><%= @role_candidate.main_aspect_c %></td>
						<td style="text-align:center"><%= @role_candidate.main_aspect_importance_c %></td>
						<td style="text-align:center"><%= @role_candidate.main_aspect_enjoyment_c %></td>
					</tr>
					<tr>
						<td><%= @role_candidate.main_aspect_d %></td>
						<td style="text-align:center"><%= @role_candidate.main_aspect_importance_d %></td>
						<td style="text-align:center"><%= @role_candidate.main_aspect_enjoyment_d %></td>
					</tr>
					<tr>
						<td><%= @role_candidate.main_aspect_e %></td>
						<td style="text-align:center"><%= @role_candidate.main_aspect_importance_e %></td>
						<td style="text-align:center"><%= @role_candidate.main_aspect_enjoyment_e %></td>
					</tr>
				</tbody>		
			</table>
		</div>

	</div>

	<div class="col-md-6">

		<div class="report-section">
			<h3><small>Main Aspects of Current Role (Manager)</small></h3><br>

			<table class="table table-hover">
				<tbody>
					<tr>
						<td style="text-align:center">1</td>
						<td><%= @role_collaborator.main_aspect_1 %></td>
					</tr>
					<tr>
						<td style="text-align:center">2</td>
						<td><%= @role_collaborator.main_aspect_2 %></td>
					</tr>
					<tr>
						<td style="text-align:center">3</td>
						<td><%= @role_collaborator.main_aspect_3 %></td>
					</tr>
					<tr>
						<td style="text-align:center">4</td>
						<td><%= @role_collaborator.main_aspect_4 %></td>
					</tr>
					<tr>
						<td style="text-align:center">5</td>
						<td><%= @role_collaborator.main_aspect_5 %></td>
					</tr>
				</tbody>		
			</table>
		</div>

	</div>
</div>

<div class="report-section">
	<h3><small>Secondary Aspects to the Current Role</small></h3>
	<p><%= simple_format(@role_candidate.secondary_aspect) %></p>
</div>

<div class="report-section">
	<h3><small>Unnecessary to the Current Role</small></h3>
	<p><%= simple_format(@role_candidate.unnecessary_aspect) %></p>
</div>

<div class="report-section">
	<h3><small>Shorter-term Development Needs</small></h3>
	<p><%= simple_format(@role_candidate.short_term_training) %></p>

	<h3><small>Medium-term Development Needs</small></h3>
	<p><%= simple_format(@role_candidate.medium_term_training) %></p>

	<h3><small>Longer-term Development Needs</small></h3>
	<p><%= simple_format(@role_candidate.long_term_training) %></p>
</div>

app/views/candidates/_tdna_report.html.erb
<a href="tdna" area_id_eq="tdna"></a>
<br>
<h3>Training &amp; Development Needs Analysis</h3><br>

<div class="report-section">

	<%= search_form_for @search, url: report_path(anchor: 'tdna') do |f| %>

	<div class="row">
		<div class="col-md-2">
			<%= f.input :area_id_eq, collection: Area.all, label: 'Area', required: false %>
		</div>
		<div class="col-md-2">
			<%= f.input :relevance_eq, collection: [0,1,2,3,4,5], label: 'Relevance', required: false %>
		</div>
		<div class="col-md-2"> 
			<%= f.input :interest_eq, collection: [0,1,2,3,4,5], label: 'Interest', required: false %>
		</div>
		<div class="col-md-2">
			<%= f.input :skill_eq, collection: [0,1,2,3,4,5], label: 'Skill', required: false %>       
		</div>
		<div class="col-md-2">
			<%= f.input :current_relevance_eq, collection: [true, false], label: 'Cur. Relevance', required: false %>
		</div>
		<div class="col-md-2">
			<%= f.input :future_relevance_eq, collection: [true, false], label: 'Fut. Relevance', required: false %>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12" style="margin-bottom:4em">
		<%= f.submit 'Search', class: "btn btn-primary" %>
		<%= link_to "Clear", report_path(anchor: 'tdna'), class: "btn btn-default", style: "margin-left:0.25em" %>
		</div>
	</div>

	<% end %>

	<br>

	<table class="table table-hover table-responsive">

	    <thead>
	    <tr>
	      <th colspan="1"></th>
	      <th colspan="3" class="candidate-columns">Candidate</th>
	      <th colspan="2" style="text-align:center">Collaborator</th>
	    </tr>
	  </thead>

	  <thead>
	    <tr>
	      <th style="width:50%">Activity</th>
	      <th style="width:10%;text-align:center" class="left-column">Cur.<br>Rel.</th>
	      <th style="width:10%;text-align:center">Int.</th>
	      <th style="width:10%;text-align:center" class="right-column">Skill</th>
	      <th style="width:10%;text-align:center">Cur.<br>Rel.</th>
	      <th style="width:10%;text-align:center">Fut.<br>Rel.</th>
	    </tr>
	  </thead>

	</table>

	<table class="table table-hover table-responsive">

	  <tbody>
	    <% @grouped_areas.each do |area, needs_analyses| %>
	      <tr class="area-row">
	        <th style="vertical-align:bottom" scope="rowgroup" colspan="4"><%= area.name %></th>
	      </tr>
	    <% needs_analyses.each do |needs_analysis| %>
	      <tr>
	        <td style="width:50%"><%= needs_analysis.activity.name %></td>
	        <td class="left-column data-column data-<%= needs_analysis.relevance %>"><%= needs_analysis.relevance %></td>
	        <td class="data-column data-<%= needs_analysis.interest %>"><%= needs_analysis.interest %></td>
	        <td class="right-column data-column data-<%= needs_analysis.skill %>"><%= needs_analysis.skill %></td>
	        <td class="data-column data-<%= needs_analysis.current_relevance %>"><%= needs_analysis.current_relevance %></td>
	        <td class="data-column data-<%= needs_analysis.future_relevance %>"><%= needs_analysis.future_relevance %></td>
	      </tr>
	    <% end %>
	  </tbody>
	  <% end %>

	</table>

</div>

app/views/candidates/collaborator_instructions.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

  <h3>TDNA Matrix<br>
  <small>for <%= @candidate.name %></small></h3>
  <br>

  <h3><small>Instructions</small></h3>

  <p>When you click the button below, you will see a matrix of three columns: a list of activities; 'Current Relevance' and 'Future Relevance'. Like this:</p>

  <%= image_tag 'tdna_matrix.png', width: '100%', class: 'instructions-screenshot' %>

  <ol class="bullets">
    <li>For each activity, please tick the box under 'Current Relevance' if that activity is relevant to <%= @candidate.first_name %>'s <strong>current</strong> role/job. Leave it unticked if you feel the activity is not relevant to <%= @candidate.first_name %>'s current role/job</li>
    <li>Similarly, please tick the box under 'Future Relevance' if that activity is relevant to <%= @candidate.first_name %>'s <strong>future</strong> role/job. Leave it unticked if you feel the activity is not relevant to <%= @candidate.first_name %>'s future role/job</li>
  </ol>

  <br>
  <!-- This is the button and backend code to ensure the role analysis questionnaire loads on click -->
  <%= form_tag edit_collaborator_needs_analyses_path do %><% @needs_analyses.each do |needs_analysis| %><div style="display:none"><%= check_box_tag "needs_analysis_ids[]", needs_analysis.id, checked: true %></div><% end %><%= submit_tag "Begin #{@candidate.first_name}'s TDNA", class: "btn btn-sm btn-primary" %><% end %>
  <!-- end -->

  </div>
</div>

app/views/candidates/index.html.erb
<table class="table table-hover table-responsive">
	<thead>
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Email</th>
			<th>Organisation</th>
			<th>Subordinate<br>Candidates</th>
			<th>Options</th>
		</tr>
	</thead>
	<tbody>
		<% @candidates.each do |c| %>
		<tr>
			<td><%= c.id %></td>
			<td><%= link_to c.name, candidate_path(c) %></td>
			<td><%= c.email %></td>
			<td><%= c.organisation_name %></td>
			<td><%= c.collaborations.count %></td>
			<td>
				<%= link_to 'Report', report_path(c), target: "blank", class: "btn btn-xs btn-primary" %>
				<% unless c.collaborations.count > 0 %>
				<%= link_to 'Delete', candidate_path(c), method: :delete, class: "btn btn-xs btn-danger", data: { confirm: "Are you sure you want to delete this candidate? This action cannot be undone." } %>
				<% end %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/candidates/instructions.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">

  <h3>TDNA Matrix<br>
  <small>for <%= current_candidate.name %></small></h3>
  <br>

  <h3><small>Instructions</small></h3>

  <p>The next page shows a list of activities and three rating columns. Like this:</p>

  <%= image_tag 'candidate_matrix.png', width: '100%', class: 'instructions-screenshot' %>

  <p>For each activity, please rate (according to the following scales): the relevance of the activity to your current role; your personal interest in that activity; and your own perceived skill/confidence in that activity.</p>

  <div class="rating-instructions">

    <p><strong>Relevance to Current Role</strong><br>
    In the first column, rate each activity where:</p>

    <div class="row">
      <div class="col-lg-3 col-lg-offset-2 col-md-4 col-md-offset-1 col-sm-4 col-sm-offset-1 col-xs-4" style="text-align:center">
        <a href='#' class="btn btn-xs btn-default">0</a><br>
        <small>means this activity is <strong>not at all</strong> relevant to my current role</small>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4" style="text-align:center">
      -
      </div>
      <div class="col-lg-3 col-md-4 col-sm-4 col-xs-4" style="text-align:center">
        <a href='#' class="btn btn-xs btn-default">5</a><br>
        <small>means this activity is <strong>essential to effective performance</strong> in my current role</small>
      </div>
    </div>

    <hr>

    <p><strong>Interest</strong><br>
    In the second column, rate each activity where:</p>

    <div class="row">
      <div class="col-lg-3 col-lg-offset-2 col-md-4 col-md-offset-1 col-sm-4 col-sm-offset-1 col-xs-4" style="text-align:center">
        <a href='#' class="btn btn-xs btn-default">0</a><br>
        <small>means I have <strong>no interest whatsoever</strong> in this activity</small>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4" style="text-align:center">
      -
      </div>
      <div class="col-lg-3 col-md-4 col-sm-4 col-xs-4" style="text-align:center">
        <a href='#' class="btn btn-xs btn-default">5</a><br>
        <small>means I have a <strong>very high degree</strong> of interest in this activity</small>
      </div>
    </div>

    <hr>

    <p><strong>Skill/Confidence</strong><br>
    In the third column, rate each activity where:</p>

    <div class="row">
      <div class="col-lg-3 col-lg-offset-2 col-md-4 col-md-offset-1 col-sm-4 col-sm-offset-1 col-xs-4" style="text-align:center">
        <a href='#' class="btn btn-xs btn-default">0</a><br>
        <small>means I have <strong>absolutely no</strong> skill/confidence in this activity</small>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4" style="text-align:center">
      -
      </div>
      <div class="col-lg-3 col-md-4 col-sm-4 col-xs-4" style="text-align:center">
        <a href='#' class="btn btn-xs btn-default">5</a><br>
        <small>means I have a <strong>very high degree</strong> of skill/confidence in this activity</small>
      </div>
    </div>

  </div>

  <p style="margin-bottom:1em">The matrix should take about <strong>20 minutes</strong> to complete, and when you are happy with your responses, simply click 'Save and Exit'.</p>

  <br>
  <!-- This is the button and backend code to ensure the TDNA matrix loads on click -->
  <%= form_tag edit_candidate_needs_analyses_path do %><% @needs_analyses.each do |needs_analysis| %><div style="display:none"><%= check_box_tag "needs_analysis_ids[]", needs_analysis.id, checked: true %></div><% end %><%= submit_tag "Click here to begin", class: "btn btn-sm btn-primary" %><% end %>
  <!-- end -->

  </div>
</div>

app/views/candidates/report.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">

		<h2>Analysis Report</h2>

		<p><%= link_to "(PDF)", report_path(@candidate, :format => 'pdf') %></p>

		<hr><br>

		<%= render 'candidates/role_report' %>

		<%= render 'candidates/tdna_report' %>

	</div>
</div>

app/views/candidates/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <div class="alert alert-warning alert-dismissable alert-welcome" role="alert">
        <h3>Instructions</h3>
        <div id="welcome-div" style="display:none">
        <ol>
          <li>Complete the <strong>Role Analysis</strong> questionnaire by clicking on 'Get Started' in the Role Analysis box. When finished, click 'Save and Exit', and you will return to this page.</li>
          <li>Complete the <strong>TDNA Matrix</strong> by clicking on 'Get Started' in the TDNA Matrix box. When finished, click 'Save and Exit', and you will return to this page again.</li>
          <% if @candidate.collaborations.count > 0 %>
          <li>Complete the Role Analysis questionnaire and TDNA Matrix for each of your colleagues listed in the <strong>Colleagues</strong> box. Click on 'Save and Exit' at the end of each to return to this page.</li>
          <li>As you complete each questionnaire, the buttons on this page will change to white indicating they have been started. You will still be able to access them by clicking again on the button.</li>
          <% end %>
          <li>When complete, click 'Sign out' at the top-right of your screen.</li>
          <li>If you need to change your sign-up details, click 'Edit Profile' at any time.</li>
        </ol>
      </div>
      <button id="hideshow-welcome" class="btn btn-sm btn-default">Show</button>
    </div>

    <script>
        $("#hideshow-welcome").click(function() {
            $("#welcome-div").slideToggle( "slow", function() {});
            $(this).text(function(i, text){ return text === "Hide" ? "Show" : "Hide"; })
        });
    </script>

    <div class="show-section">
      <h3>Role Analysis</h3>
      <p>The role analysis questionnaire sets the context in terms of your current role and, if known, your next role. By using your responses to this, we can ensure that any recommendations we make in terms of training and development fit with your current (and future) needs.</p>
      <!-- This is the button and backend code to ensure the role analysis questionnaire loads on click -->
      <% @role_candidates.each do |r| %>
      <% if current_candidate.role_visits.present? %>
      <%= link_to "Edit Responses", edit_role_candidate_path(r.id), class: "btn btn-sm btn-default" %>  
      <% else %>
      <%= link_to "Get Started", edit_role_candidate_path(r.id), class: "btn btn-sm btn-primary" %>
      <% end %>
      <% end %>
      <!-- end -->
    </div>

    <div class="show-section">
      <h3>TDNA Matrix</h3>
      <p>Training &amp; Development Needs Analysis (TDNA) assesses your self-perceived capabilities in everyday activities. By analysing your responses to this, we can recommend training and development that will support your current and future roles.</p>
      <% if current_candidate.tdna_visits.present? %>
      <%= link_to "Edit Responses", instructions_path, class: "btn btn-sm btn-default" %>
      <% else %>
      <%= link_to "Get Started", instructions_path, class: "btn btn-sm btn-primary" %>
      <% end %>
    </div>

    <% if @candidate.collaborations.count > 0 %>
    
    <div class="show-section">

      <h3>Colleagues</h3>
      <p>For each of your colleagues listed below, please complete their individual Role Analysis and TDNA Matrix.</p>

      <table class="table table-hover table-responsive">
        <thead>
          <th style="width:40%">Colleague</th>
          <th style="width:30%">Role Analysis</th>
          <th style="width:30%">TDNA Matrix</th>
        </thead>
        <tbody>
          <% @role_collaborator.each do |r| %>
          <tr>
            <td style="vertical-align:middle"><%= r.candidate.name %></td>
            <td>
              <!-- Role Analysis button -->
              <% if r.candidate.collaborator_role_visits.present? %>
              <%= link_to 'Edit', edit_role_collaborator_path(r.id), class: "btn btn-xs btn-default" %>
              <% else %>
              <%= link_to 'Start', edit_role_collaborator_path(r.id), class: "btn btn-xs btn-primary" %>
              <% end %>
            </td>
            <td>
              <!-- TDNA button -->
              <% if r.candidate.collaborator_tdna_visits.present? %>
              <%= link_to 'Edit', collaborator_instructions_path(r.candidate_id), class: 'btn btn-xs btn-default' %>
              <% else %>
              <%= link_to 'Start', collaborator_instructions_path(r.candidate_id), class: 'btn btn-xs btn-primary' %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>        
      
    </div>

    <% end %>

  </div>
</div>