config/routes.rb
Rails.application.routes.draw do

  devise_for :administrators
  resources :role_collaborators

  resources :role_candidates

  resources :needs_analyses do
    collection do
      post 'edit_candidate' => 'needs_analyses#edit_candidate', as: :edit_candidate
      put 'update_candidate' => 'needs_analyses#update_candidate', as: :update_candidate
      post 'edit_collaborator' => 'needs_analyses#edit_collaborator', as: :edit_collaborator
      put 'update_collaborator' => 'needs_analyses#update_collaborator', as: :update_collaborator
    end
  end

  resources :activities

  devise_for :candidates, :controllers => { :registrations => :registrations }
  resources :candidates, only: [:index, :show, :destroy]
  resources :collaborations

  get '/candidates/:id(.:format)/collaborator' => 'candidates#collaborator_instructions', :as => :collaborator_instructions
  get '/candidates/:id(.:format)/instructions' => 'candidates#instructions', :as => :instructions
  get '/candidates/:id(.:format)/report' => 'candidates#report', :as => :report
  get '/admin' => 'pages#admin'

  root 'pages#home'

end

app/views/layouts/_candidate_banner.html.erb
<nav class="navbar navbar-default candidate-banner">
    
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to current_candidate.name, candidate_path(current_candidate), class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<li><%= link_to 'Edit Profile', edit_candidate_registration_path(current_candidate) %></li>
      	<li><%= link_to 'Sign out', destroy_candidate_session_path, method: :delete %></li>
      </ul>

    </div><!-- /.navbar-collapse -->

</nav>

app/views/layouts/_footer.html.erb
<div class="footer-push"></div>

<div class="footer">
    <div class="text-muted">
    	&copy; R&amp;S Hughes Limited <%= Time.now.year %> 
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
    
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'TDNA', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<% if candidate_signed_in? %>
        	<li class=""><%= link_to 'Get Started', '#' %></li>
        <% end %>
        <% if administrator_signed_in? %>
          <li class="<%= 'active' if current_page?(candidates_path) %>"><%= link_to 'Candidates', candidates_path %></li>
          <li class="<%= 'active' if current_page?(collaborations_path) %>"><%= link_to 'Collaborations', collaborations_path %></li>
          <li class="<%= 'active' if current_page?(needs_analyses_path) %>"><%= link_to 'TDNAs', needs_analyses_path %></li>
          <li class="<%= 'active' if current_page?(role_candidates_path) %>"><%= link_to 'Roles (Candidate)', role_candidates_path %></li>
          <li class="<%= 'active' if current_page?(role_collaborators_path) %>"><%= link_to 'Roles (Collaborator)', role_collaborators_path %></li>
          <li class="<%= 'active' if current_page?(activities_path) %>"><%= link_to 'Activities', activities_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<% if candidate_signed_in? %>
      		<li><%= link_to current_candidate.name, edit_candidate_registration_path(current_candidate) %></li>
        	<li><%= link_to "Sign out", destroy_candidate_session_path, method: :delete %></li>
        <% elsif administrator_signed_in? %>
          <li><%= link_to current_administrator.email, edit_administrator_registration_path(current_administrator) %></li>
          <li><%= link_to "Sign out", destroy_administrator_session_path, method: :delete %></li>
        <% else %>
        	<li><%= link_to 'Sign up', new_candidate_registration_path %></li>
        	<li><%= link_to 'Sign in', new_candidate_session_path %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TDNA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container-fluid">

		<%= render 'layouts/header' if administrator_signed_in? unless @disable_nav %>
		<%= render 'layouts/candidate_banner' if candidate_signed_in? %>
		<%= flash_messages %>
		<div class="yield-div"><%= yield %></div>
		<%= render 'layouts/footer' if candidate_signed_in? or administrator_signed_in? unless @disable_nav %>
			
	</div>

</body>
</html>